# Homework on Statistical Learning Theory

<b>Deadline:</b> 24.12.2018, 9 a.m. (there would be no soft deadline)

<b>How to hang in?</b> You need to put your Jupyter Notebook to GitHub repo and send link in Telegram to <b>@CroCode</b>

In [13]:
# Artem Volgin

### Block №1. Combinatorics and Probability Theory

You can use LaTeX expressions in order to provide formulas: https://en.wikibooks.org/wiki/LaTeX

1) In how many ways can the letters of the word PROBABILITY be rearranged such that all I’s and P’s appear in the middle?

<b>Total:</b> 1 point

Because there are two 'I' in our word, we need to consider 3 outcomes there 'I' or 'P' appear in the middle. We have 11 letters in word PROBABILITY, so then we fixed one letter in in the middle we left with 10 letters. In case of 'fixed' P we need to account of repeating 'I', also we need to handle repeating 'B's. Considering all these condintions number of combinations will be equal to:

$$\frac{10!}{2!2!} + 2\times\frac{10!}{2!} = 7257600$$

In [7]:
from math import factorial as fact

int(fact(10)/fact(2)*fact(2) + 2*(fact(10)/fact(2)))

7257600

2) The probability of having defect (at least 1 defective product) in batch of 100 products is 63.2%. Find the probability of having less than 3 defective products in such a batch.

<i>Hint:</i> use idea of Poisson distribution (https://en.wikipedia.org/wiki/Poisson_distribution)

<b>Total:</b> 1.5 points

At first we need to find parameter $\lambda$ of Poisson distribution for our case. <br> 
We know that $P(X\geq1) = 0.632$, so $P(X=0) = 1 - P(X\geq1) = 0.368$. <br> 
According to the formula of Poisson distribution $P(X=0) = e^{-\lambda}*\frac{\lambda^0}{0!} = e^{-\lambda}$ <br>
$\frac{1}{e^\lambda} = 0.368$ <br> 
$e^\lambda = 2.717$ <br> 
$\lambda\approx 1$

$P(X<3) = P(X=0) + P(X=1) + P(X=2)$

If we use Poisson distribution formula for $P(X=1)$ and $P(X=2) we will get:

$P(X<3) = 0.368 + 0.367 + 0.1835 = 0.9185$

### Block №2. Data Structures and Algorithms

<b><i>NB!</i></b> Here you need to provide solution having minimal memory and runtime complexity in terms of Big O notation.

3) Suggest an algorithm that resets all elements in the column <i>i</i> and the row <i>j</i> of the matrix M to zeros if the element in the <i>(i, j)</i> cell is zero. Provide solution having minimal memory and runtime complexity in terms of Big O notation.

<b>Input:</b> matrix M

<b>Output:</b> modified according to condition matrix M

<b>Total:</b> 2 points

In [62]:
import numpy as np
  
def changeToZero(mat):
    rowL = len(mat)
    colL = len(mat[0])
    
    # By default all values of row and col are equal to 1  
    row = [1] * rowL  
    col = [1] * colL 
        
  
    # Storing the rows and columns to be marked as 0 in created arrays 
    for i in range(0, rowL) :         
        for j in range(0, colL) : 
            if (mat[i][j] == 0) : 
                row[i] = 0
                col[j] = 0
              
    # Transforming intial matrix with row and col  
    for i in range(0, rowL) :        
        for j in range(0, colL): 
            if ( row[i] == 0 or col[j] == 0 ) : 
                mat[i][j] = 0
                  

mat = [ [1, 1, 1, 1], 
        [1, 1, 1, 1], 
        [0, 0, 1, 0] ]  
  
print("Initial Matrix") 
print(np.matrix(mat))
  
changeToZero(mat)

print() 
print("Transformed Matrix") 
print(np.matrix(mat))


# Memory complexity: O(M + N)
# Runtime complexity: O(M*N)

Initial Matrix
[[1 1 1 1]
 [1 1 1 1]
 [0 0 1 0]]

Transformed Matrix
[[0 0 1 0]
 [0 0 1 0]
 [0 0 0 0]]


4) Imagine you have a square picture, each pixel of which can be black or white (you can interpret it as binary matrix). Develop an algorithm for finding the maximum sub-square consisting of only black pixels.

<b>Input:</b> binary matrix M (contains only 0-1 elements)

<b>Output:</b> <i>((a1, b1),(a2, b2))</i> where <i>(a1, b1)</i> and <i>(a2, b2)</i> stay for coordinates of upper-left and lower-right sub-square corners respectively

<b>Total:</b> 2.5 points

In [44]:
# put your code with comments here

# Memory complexity: ...
# Runtime complexity: ...

5) Imagine series of integer numbers having only 3, 5 or 7 of some power in their factorization (i.e. 1, 3, 5, 7, 9, 15 etc.). Given k you're asked to return k-th number in this series.

<i>Helpful link</i>: https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic

<b>Input:</b> integer number k

<b>Output:</b> k-th number of series

<b>Total:</b> 3 points

In [61]:

# Finding largest divisible power
def largestDivision(a, b): 
    while a % b == 0: 
        a /= b 
    return a  
  
# Checking if a number has 3, 5 or 7 of some power in their factorization
def isFactor(n): 
    n = largestDivision(n, 3) 
    n = largestDivision(n, 5) 
    n = largestDivision(n, 7)
    if n == 1:
        a = 1
    else:
        a = 0
    return a
  
# Getting the kth element in the series 
def kthNumber(k): 
    i = 1
    count = 1
    
    # Checking for all integers and adding to k number of found numbers that satisfied our coundintion until it reach count
    # In i we will have number which we looking for
    while k > count: 
        i += 1
        if isFactor(i): 
            count += 1
    return i 
  

kthNumber(30) 

# Memory complexity: O(1)
# Runtime complexity: O(N*N)

525